### ISSUE TITLE
Unable to install using cli

### ISSUE THREAD

**Issue by aurora** [rafaelmaiolla/remote-vscode#15]
I am not sure if this is an issue of your extension or if it's something in vs code, i have this problem only with your extension so far, though: i am unable to install your extension using the cli:

    code --install-extension rafaelmaiolla.remote-vscode

This results in the output below. Installing directly from vs code works, though. I've tried this with Linux and Mac OS X, so the problem doesn't seem to be platform specific.

Output of the above command:

    Found 'rafaelmaiolla.remote-vscode' in the marketplace.
    Installing...
    WARNING: Promise with no error callback:19
    { exception: null,
    error:
    Error: Invalid package /Users/harald/.vscode/extensions/rafaelmaiolla.remote-vscode-0.1.8/.vscode-test/VSCode-linux-x64/resources/atom.asar
        at invalidArchiveError (ELECTRON_ASAR.js:149:19)
        at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:205:16)
        at WriteStream.open (fs.js:2094:6)
        at new WriteStream (fs.js:2080:10)
        at Object.fs.createWriteStream (fs.js:2035:10)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11353
        at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:30926)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11317
        at Object._ [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:23742)
        at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:27320),
    promise:
    { _oncancel: null,
        _nextState: null,
        _state:
        { name: 'error',
            enter: [Function: enter],
            cancel: [Function: a],
            done: null,
            then: null,
            _completed: [Function: a],
            _error: [Function: a],
            _notify: [Function: m],
            _progress: [Function: a],
            _setCompleteValue: [Function: a],
            _setErrorValue: [Function: a] },
        _listeners: null,
        _value:
        Error: Invalid package /Users/harald/.vscode/extensions/rafaelmaiolla.remote-vscode-0.1.8/.vscode-test/VSCode-linux-x64/resources/atom.asar
            at invalidArchiveError (ELECTRON_ASAR.js:149:19)
            at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:205:16)
            at WriteStream.open (fs.js:2094:6)
            at new WriteStream (fs.js:2080:10)
            at Object.fs.createWriteStream (fs.js:2035:10)
            at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11353
            at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:30926)
            at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11317
            at Object._ [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:23742)
            at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:27320),
        _isException: false,
        _errorId: 19,
        done: [Function: done],
        then: [Function: then] },
    handler: undefined,
    id: 19,
    parent: undefined }
    /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4
    (function(){var e=["exports","require","vs/base/common/platform","vs/base/common/types","vs/base/common/uri","vs/base/common/winjs.base","vs/base/common/arrays","vs/base/common/errors","vs/nls!vs/platform/environment/node/argv","vs/base/common/objects","vs/platform/environment/node/argv","vs/platform/package","path","vs/platform/product","os","minimist","assert","vs/base/common/winjs.base.raw","vs/nls!vs/code/node/cli","child_process","vs/code/node/cli","vs/nls"],t=function(t){for(var n=[],r=0,o=t.length;r<o;r++)n[r]=e[t[r]];return n};define(e[6],t([1,0]),function(e,t){"use strict";function n(e,t){return void 0===t&&(t=0),e[e.length-(1+t)]}function r(e,t){for(var n=0,r=e.length;n<r;n++)t(e[n],function(){e.splice(n,1),n--,r--})}function o(e,t,n){if(void 0===n&&(n=function(e,t){return e===t}),e.length!==t.length)return!1;for(var r=0,o=e.length;r<o;r++)if(!n(e[r],t[r]))return!1;return!0}function i(e,t,n){for(var r=0,o=e.lengt

    Error: Invalid package /Users/harald/.vscode/extensions/rafaelmaiolla.remote-vscode-0.1.8/.vscode-test/VSCode-linux-x64/resources/atom.asar

    Error: Invalid package /Users/harald/.vscode/extensions/rafaelmaiolla.remote-vscode-0.1.8/.vscode-test/VSCode-linux-x64/resources/atom.asar
        at invalidArchiveError (ELECTRON_ASAR.js:149:19)
        at Object.module.(anonymous function) [as open] (ELECTRON_ASAR.js:205:16)
        at WriteStream.open (fs.js:2094:6)
        at new WriteStream (fs.js:2080:10)
        at Object.fs.createWriteStream (fs.js:2035:10)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11353
        at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:30926)
        at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cliProcessMain.js:7:11317
        at Object._ [as _notify] (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:23742)
        at Object.enter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:27320)
        at Timeout._onTimeout (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/node/cli.js:4:7323)
        at tryOnTimeout (timers.js:232:11)
        at Timer.listOnTimeout (timers.js:202:5)

**Comment by rafaelmaiolla** [comment]
I can see the same issue, will investigate.

**Comment by rafaelmaiolla** [comment]
This is fixed in version 1.0.1.  Please uninstall the old extension and try to install the new version.
