### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by HardlyMirage** [rafaelmaiolla/remote-vscode#21]
I get an error when trying to open a remote javascript file. See developer console log below:

```
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] extension - [39mstartServer
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] Server - [39msetPort 52698
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] Server - [39msetHost 127.0.0.1
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] Server - [39mstart false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] Server - [39misOnline
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:16:46.723] [DEBUG] Server - [39misOnline? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.723] [TRACE] Server - [39mstop
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.724] [TRACE] Server - [39misOnline
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:16:46.724] [DEBUG] Server - [39misOnline? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.724] [TRACE] Server - [39msetOnline false
extensionHost.ts:284 [Extension Host] [32m[2017-04-13 02:16:46.724] [INFO] Server - [39mRestarting server
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.724] [TRACE] Server - [39mgetPort 52698
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.724] [TRACE] Server - [39mgetHost NaN
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.724] [TRACE] Server - [39monServerClose
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.725] [TRACE] Server - [39monServerListening
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:16:46.726] [TRACE] Server - [39msetOnline true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.437] [TRACE] Server - [39monServerConnection
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.437] [TRACE] Session - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.437] [TRACE] Session - [39msend VSCode 1
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.437] [TRACE] Session - [39misOnline
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.437] [DEBUG] Session - [39misOnline? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Session - [39monSocketData <Buffer 6f 70 65 6e>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Session - [39mparseChunk <Buffer 6f 70 65 6e>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Command - [39mconstructor open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Command - [39msetName open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.752] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.752] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Session - [39monSocketData <Buffer 0a 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 69 70 2d 31 37 32 2d 33 31 2d 33 31 2d 38 35 3a 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 72 65 61 6c 2d 70 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] Session - [39mparseChunk <Buffer 0a 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 69 70 2d 31 37 32 2d 33 31 2d 33 31 2d 38 35 3a 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 72 65 61 6c 2d 70 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.752] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.752] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:31.752] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:31.752] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Session - [39monSocketData <Buffer 64 61 74 61 2d 6f 6e 2d 73 61 76 65 3a 20 79 65 73 0a 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Session - [39mparseChunk <Buffer 64 61 74 61 2d 6f 6e 2d 73 61 76 65 3a 20 79 65 73 0a 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.076] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.076] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Command - [39maddVariable data-on-save yes
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Command - [39maddVariable re-activate yes
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Command - [39maddVariable token subscribe.js
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] RemoteFile - [39msetDataSize 3988
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Command - [39mgetVariable token
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.076] [TRACE] Command - [39mgetVariable display-name
extensionHost.ts:284 [Extension Host] Uncaught Exception:  TypeError: Cannot read property 'split' of undefinedd.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] TypeError: Cannot read property 'split' of undefined
    at RemoteFile.setDisplayName (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:23:46)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:53:37)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.095] [TRACE] Session - [39monSocketData <Buffer 76 61 72 20 63 75 72 72 65 6e 74 5f 66 73 2c 20 6e 65 78 74 5f 66 73 2c 20 70 72 65 76 69 6f 75 73 5f 66 73 2c 0a 09 6c 65 66 74 2c 20 6f 70 61 63 69 ... >
shell.ts:475 Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at RemoteFile.setDisplayName (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:23:46)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:53:37)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:475 fd must be a file descriptor: TypeError: fd must be a file descriptor
    at TypeError (native)
    at Object.fs.closeSync (fs.js:609:18)
    at Object.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\node_modules\graceful-fs\graceful-fs.js:51:27)
    at RemoteFile.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:65:12)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:67:29)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.095] [TRACE] Session - [39mparseChunk <Buffer 76 61 72 20 63 75 72 72 65 6e 74 5f 66 73 2c 20 6e 65 78 74 5f 66 73 2c 20 70 72 65 76 69 6f 75 73 5f 66 73 2c 0a 09 6c 65 66 74 2c 20 6f 70 61 63 69 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.095] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.096] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.096] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.096] [DEBUG] RemoteFile - [39misEmpty? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.097] [TRACE] RemoteFile - [39mappendData 3991
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.097] [DEBUG] RemoteFile - [39mwritenDataSize 3988
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.098] [TRACE] RemoteFile - [39mwriteSycn
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.098] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:32.098] [DEBUG] RemoteFile - [39misReady? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:32.098] [TRACE] RemoteFile - [39mcloseSync
extensionHost.ts:284 [Extension Host] Uncaught Exception:  TypeError: fd must be a file descriptord.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] TypeError: fd must be a file descriptor
    at TypeError (native)
    at Object.fs.closeSync (fs.js:609:18)
    at Object.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\node_modules\graceful-fs\graceful-fs.js:51:27)
    at RemoteFile.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:65:12)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:67:29)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)d.logExtensionHostMessage @ extensionHost.ts:284(anonymous function) @ extensionHost.ts:139emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.350] [TRACE] Server - [39monServerConnection
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.350] [TRACE] Session - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.350] [TRACE] Session - [39msend VSCode 1
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.350] [TRACE] Session - [39misOnline
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.350] [DEBUG] Session - [39misOnline? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.679] [TRACE] Session - [39monSocketData <Buffer 6f 70 65 6e 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.679] [TRACE] Session - [39mparseChunk <Buffer 6f 70 65 6e 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.679] [TRACE] Command - [39mconstructor open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.680] [TRACE] Command - [39msetName open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.680] [TRACE] RemoteFile - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.680] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.680] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.680] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.681] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.681] [TRACE] Session - [39monSocketData <Buffer 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 69 70 2d 31 37 32 2d 33 31 2d 33 31 2d 38 35 3a 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 72 65 61 6c 2d 70 61 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.681] [TRACE] Session - [39mparseChunk <Buffer 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 69 70 2d 31 37 32 2d 33 31 2d 33 31 2d 38 35 3a 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 72 65 61 6c 2d 70 61 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.681] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.681] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.681] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.682] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.682] [TRACE] Command - [39maddVariable display-name ip-XX-XX-XX-XX:subscribe.js
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.682] [TRACE] Command - [39maddVariable real-path /opt/pay/public/js/subscribe.js
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.682] [TRACE] Command - [39maddVariable data-on-save yes
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:51.682] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:51.682] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.000] [TRACE] Session - [39monSocketData <Buffer 0a 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 64 61 74 61 3a 20 33 39 38 38 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.000] [TRACE] Session - [39mparseChunk <Buffer 0a 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 64 61 74 61 3a 20 33 39 38 38 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.001] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.001] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.001] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.001] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.001] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.001] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.001] [TRACE] Session - [39monSocketData <Buffer 76 61 72 20 63 75 72 72 65 6e 74 5f 66 73 2c 20 6e 65 78 74 5f 66 73 2c 20 70 72 65 76 69 6f 75 73 5f 66 73 2c 0a 09 6c 65 66 74 2c 20 6f 70 61 63 69 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.001] [TRACE] Session - [39mparseChunk <Buffer 76 61 72 20 63 75 72 72 65 6e 74 5f 66 73 2c 20 6e 65 78 74 5f 66 73 2c 20 70 72 65 76 69 6f 75 73 5f 66 73 2c 0a 09 6c 65 66 74 2c 20 6f 70 61 63 69 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.002] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.002] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] Command - [39maddVariable var current_fs, next_fs, previous_fs, 
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] Command - [39maddVariable left, opacity, scale, 
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] Command - [39maddVariable animating; 
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:17:52.002] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:17:52.002] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:53.790] [TRACE] Server - [39monServerConnection
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:53.790] [TRACE] Session - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:53.790] [TRACE] Session - [39msend VSCode 1
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:53.790] [TRACE] Session - [39misOnline
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:53.790] [DEBUG] Session - [39misOnline? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.098] [TRACE] Session - [39monSocketData <Buffer 6f 70 65 6e>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.098] [TRACE] Session - [39mparseChunk <Buffer 6f 70 65 6e>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.098] [TRACE] Command - [39mconstructor open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.098] [TRACE] Command - [39msetName open
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.098] [TRACE] RemoteFile - [39mconstructor
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] Session - [39monSocketData <Buffer 0a 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 48 0a 72 65 61 6c 2d 70 61 74 68 3a 20 2f 6f 70 74 2f 70 61 79 2f 70 75 62 6c 69 63 2f 6a 73 2f 73 75 62 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] Session - [39mparseChunk <Buffer 0a 64 69 73 70 6c 61 79 2d 6e 61 6d 65 3a 20 48 0a 72 65 61 6c 2d 70 61 74 68 3a 20 2f 6f 70 74 2f 70 61 79 2f 70 75 62 6c 69 63 2f 6a 73 2f 73 75 62 ... >
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] Session - [39monSocketData <Buffer 0a 64 61 74 61 2d 6f 6e 2d 73 61 76 65 3a 20 79 65 73 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] Session - [39mparseChunk <Buffer 0a 64 61 74 61 2d 6f 6e 2d 73 61 76 65 3a 20 79 65 73 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misEmpty
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misEmpty? true
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.114] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.114] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.438] [TRACE] Session - [39monSocketData <Buffer 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 64 61 74 61 3a 20 33 39 38 38 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.438] [TRACE] Session - [39mparseChunk <Buffer 72 65 2d 61 63 74 69 76 61 74 65 3a 20 79 65 73 0a 74 6f 6b 65 6e 3a 20 73 75 62 73 63 72 69 62 65 2e 6a 73 0a 64 61 74 61 3a 20 33 39 38 38 0a>
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.438] [TRACE] RemoteFile - [39misReady
extensionHost.ts:284 [Extension Host] [36m[2017-04-13 02:18:54.438] [DEBUG] RemoteFile - [39misReady? false
extensionHost.ts:284 [Extension Host] [34m[2017-04-13 02:18:54.438] [TRACE] RemoteFile - [39misEmpty
shell.ts:475 Cannot read property 'split' of undefined: TypeError: Cannot read property 'split' of undefined
    at RemoteFile.setDisplayName (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:23:46)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:53:37)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)e.onUnexpectedError @ shell.ts:475(anonymous function) @ shell.ts:435e.onUnexpectedError @ errors.ts:68o @ errors.ts:88t.onUnexpectedExtHostError @ mainThreadErrors.ts:13e.handle @ abstractThreadService.ts:34s @ ipcRemoteCom.ts:275f @ ipcRemoteCom.ts:231_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
shell.ts:475 fd must be a file descriptor: TypeError: fd must be a file descriptor
    at TypeError (native)
    at Object.fs.closeSync (fs.js:609:18)
    at Object.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\node_modules\graceful-fs\graceful-fs.js:51:27)
    at RemoteFile.closeSync (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\RemoteFile.js:65:12)
    at Session.parseChunk (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:67:29)
    at Session.onSocketData (C:\Users\Dell\.vscode\extensions\rafaelmaiolla.remote-vscode-1.0.1\out\src\lib\Session.js:23:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

VSCode version: 1.11.1
Remote VSCode extension: 1.0.1
Remote rmate version: 1.5.9
Remote OS: Ubuntu 14.04.3 LTS

**Comment by rafaelmaiolla** [comment]
Can you send me the link for the rmate version you are using? Is it shell, ruby?

**Comment by HardlyMirage** [comment]
It's Ruby: https://github.com/textmate/rmate

I just did a `gem install rmate`

**Comment by rafaelmaiolla** [comment]
Are you using any parameter? Like `-m`

**Comment by HardlyMirage** [comment]
No, the full command is just `rmate file.js`
